#!bin/bash
echo "
----->[Updating system...]
"
sleep 3
xbps-install -Suy
echo "
----->[Installing libraries...]
"
xbps-install -Sy void-repo-multilib libgcc-32bit libstdc++-32bit screen wget curl
echo "
----->[Installing steamcmd...]
"
sleep 3
echo "
----->Create a password for the server user:"
read x
y=$(openssl passwd -6 $x)
sudo useradd -p $y rustds
mkdir /home/rustds/steamcmd
mkdir /home/rustds/steamcmd/rust
wget http://media.steampowered.com/client/steamcmd_linux.tar.gz
tar -xf steamcmd_linux.tar.gz -C /home/rustds/steamcmd
rm -rf steamcmd_linux.tar.gz
echo "
----->[Installing RUST server...]
"
sleep 3
bash /home/rustds/steamcmd/steamcmd.sh +login anonymous +force_install_dir /home/rustds/steamcmd/rust +app_update 258550 +exit
echo "
----->[Installing our tools for RUST server...]
"
sleep 3
git clone https://github.com/velimvim/rust_tool
tar -xf scripts.tar.gz /home/rustds/steamcmd/rust
mv /home/rustds/steamcmd/rust/rust_tool/* /home/rustds/steamcmd/rust/
rm -rf /home/rustds/steamcmd/rust/rust_tool
rm -rf scripts.tar.gz
mv /home/rustds/steamcmd/rust/scripts/rust /usr/local/bin
echo "
----->[Completed.]
(Visit konataa.ru)
"
